suppressPackageStartupMessages(library(Signac))
suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(argparse))
suppressPackageStartupMessages(library(GenomicRanges))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(Matrix))
suppressPackageStartupMessages(library(pbapply, include.only = c("pblapply")))
suppressPackageStartupMessages(library(usedist))
suppressPackageStartupMessages(library(dplyr))

parser <- ArgumentParser()

parser$add_argument("--rna_matrix",
    help="[REQUIRED] Path to .rds file with RNA matrix generated by Signac")
parser$add_argument("--gene_gene_pairs_file",
    help="[REQUIRED] Path to file with gene-gene pairs")
parser$add_argument("--outfile", default = ".",
    help = "[REQUIRED] Path to file to output co-expressions")

args <- parser$parse_args()

rna_matrix = args$rna_matrix
gene_gene_pairs_file = args$gene_gene_pairs_file
outfile = args$outfile

LinkGeneGenePairs <- function(rna_matrix_file,
    gene_gene_pairs_file, min.cells = 10, outfile = NULL) 
{
    
        # Read gene data
        gene.data <- readRDS(rna_matrix_file)
    
        # Get candidate gene-gene pairs
        gene_gene_pairs = read.table(gene_gene_pairs_file, sep = "\t", header = TRUE)
    
        gene_gene_pairs$tested = 1
        gene_gene_pairs = gene_gene_pairs %>% distinct()
        gene_gene_pairs = pivot_to_numeric_matrix(gene_gene_pairs, gene1, gene2, tested)
        print("Created pair matrix!")
    
        if (sum(gene_gene_pairs) == 0) {
            stop("No genes fall within distance threshold\n")
        }
    
        # Test gene-gene associations
        genes.use <- colnames(x = gene_gene_pairs)
        gene.T <- t(x = gene.data)
        coef.vec <- c()
        gene.vec <- c()
    
        res <- pblapply(X = seq_along(along.with = genes.use), FUN = function(i) {
            focal.gene = genes.use[[i]]
            comp.genes <- as.logical(x = gene_gene_pairs[, focal.gene])
            comp.genes <- rownames(gene_gene_pairs)[comp.genes]
            focal.gene.expression <- t(x = gene.data[focal.gene, , drop = FALSE])
            if (length(comp.genes) < 2) {
                return(list(gene2 = NULL, coef = NULL))
            }
            else {
                gene.exp <- gene_T[, comp.genes, drop = FALSE]
                coef.result <- cor(gene.exp, focal.gene.expression)[,1]
                names(x = coef.result) <- colnames(x = gene.exp)
                if (length(x = coef.result) == 0) {
                    return(list(gene = NULL, coef = NULL))
                } else {
                    gene.vec <- c(gene.vec, rep(i, length(x = coef.result)))
                    coef.vec <- c(coef.vec, coef.result)
                    return(list(gene = gene.vec, coef = coef.vec))
                }
            }
        })

        gene.vec <- do.call(what = c, args = lapply(X = res, FUN = `[[`, 
            1))
        coef.vec <- do.call(what = c, args = lapply(X = res, FUN = `[[`, 
            2))

        gene.key <- seq_along(along.with = unique(x = names(x = coef.vec)))
        names(x = gene.key) <- unique(x = names(x = coef.vec))
        coef.matrix <- sparseMatrix(i = gene.vec, j = gene.key[names(x = coef.vec)], 
            x = coef.vec, dims = c(length(x = genes.use), max(gene.key)))
        rownames(x = coef.matrix) <- genes.use
        colnames(x = coef.matrix) <- names(x = gene.key)
        
        # convert to triplet form
      dgtm <- as(object = coef.matrix, Class = "TsparseMatrix")

      # Create results dataframe
      df <- data.frame(
        gene1 = rownames(x = coef.matrix)[dgtm@i + 1],
        gene2 = colnames(x = coef.matrix)[dgtm@j + 1],
        correlation = dgtm@x
      )

      if (!is.null(x = outfile)) {
          out_dir <- dirname(outfile)
          if (!dir.exists(out_dir)) {
              print(sprintf("Creating directory"))
              dir.create(out_dir, recursive = TRUE)
          }
          write.table(df, outfile, sep = "\t", row.names = FALSE, quote = FALSE)
      } else {
          return(df)
      }
}

LinkGeneGenePairs(rna_matrix,
                  gene_gene_pairs_file, outfile = outfile)